<a href="https://colab.research.google.com/github/selimsurucu/numpy/blob/master/numpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kütüphanesinin set edilmesi

In [0]:
import numpy as np


Numpy'da array tanımlama

In [0]:
#1*4 lük bir array tanımı
myArray=np.array([1,2,3,4]) 

Array'ın boyutunu öğrenme

In [9]:
print(myArray.shape)

(4,)


Array'i yeniden boyunlandırma

In [11]:
reMyArray = myArray.reshape(2,2)
reMyArray

array([[1, 2],
       [3, 4]])

Array'ın (Matrisin) dimension'ı bulma

In [12]:
print(reMyArray.ndim)

2


Array'deki elemanların dataType 

In [13]:
print(reMyArray.dtype.name)

int64


Array'în eleman sayısı

In [14]:
print(reMyArray.size)

4


2 boyutlu array tanımlama

In [16]:
myArray2 = np.array([ [1,2,3],[2,3,4] ])
myArray2

array([[1, 2, 3],
       [2, 3, 4]])

In [20]:
print(myArray2.shape)

(2, 3)


3 boyutlu Array tanımlama

In [18]:
myArray3 = np.array([ [1,2,3],[4,5,6],[7,8,9]])
myArray3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(myArray3.shape)

(3, 3)


0 matrisi oluşturma . Genelde sistemden yer ayrılması için kullanılır.

In [21]:
myZeros = np.zeros((3,3))
myZeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Matris'e deger atama/ değeri güncelleme

In [23]:
myZeros[0][2] = 11
myZeros

array([[ 0.,  0., 11.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

1 matrisi (Birim) matrisi oluşturma

In [25]:
myOnes = np.ones((3,3))
myOnes

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Matrisi datasız yani boş oluşturma

In [28]:
myEmpty = np.empty((1,3))
myEmpty

array([[0.39215686, 0.70980392, 0.80392157]])

Belli bir aralıkta sayılar ile array oluşturma

In [31]:
myArange = np.arange(5,95,7) #ilk parametre dahil, 2 . parametre dahil değil , 3.parametre aralık. yani 1. ve 2.parametreler arasında ki sayıları 3.parametre artış miktarı olarak yazdırmak.
myArange

array([ 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89])

Belirli bir aralıkta, verilen sayı kadar değer öğretme

In [33]:
myLinspace = np.linspace(5,80,30)
myLinspace

array([ 5.        ,  7.5862069 , 10.17241379, 12.75862069, 15.34482759,
       17.93103448, 20.51724138, 23.10344828, 25.68965517, 28.27586207,
       30.86206897, 33.44827586, 36.03448276, 38.62068966, 41.20689655,
       43.79310345, 46.37931034, 48.96551724, 51.55172414, 54.13793103,
       56.72413793, 59.31034483, 61.89655172, 64.48275862, 67.06896552,
       69.65517241, 72.24137931, 74.82758621, 77.4137931 , 80.        ])