<a href="https://colab.research.google.com/github/selimsurucu/numpy/blob/master/NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kütüphanesini import ediyoruz.

In [0]:
import numpy as np

Yeni bir array(dizi) tanımlayayım

In [0]:
myArray = np.array([1,2,3,4,5,6,7,8,9,10]) #tek boyutludur.

Diziler(Array) 0'dan saymaya başlar. Elemanlar buna göre ekrana yazdırılır.

ilk elemanı yazdırmak

In [0]:
print(myArray[0])

1


Dizinin boyutunu öğrenmek :

In [0]:
print(myArray.size)

10


Dizinin son elemanını yazdırmak

In [0]:
print(myArray[myArray.size - 1] ) #0 dan başladığı için 1 çıkardık.

10


Dizinin ilk dört elemanına ulaşmak.

In [0]:
print(myArray[:4]) #Her zaman ilk parametre dahil, 2. parametre dahil değildir. ilk parametre verilmemişse bu sıfırdır. ikinci parametre verilmemişse dizinin sonundaki elemanın index'i olur.

[1 2 3 4]


Bir dizideki elemanları 1er eleman atlayarak yazdıralım. (Yani 0.-2. -4. ... indexlerdeki elemanları yazdılarım.)

In [0]:
print(myArray[::2])

[1 3 5 7 9]


Diziyi tersten yazdırmak

In [0]:
print(myArray[::-1])

[10  9  8  7  6  5  4  3  2  1]


2 boyutlu dizi tanımlama

In [3]:
myNewArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
myNewArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

2 boyutlu bir dizide elemana ulaşmak

In [0]:
print(myNewArray[1,4]) # ilk parametre satırın index'i (1) , ikinci parametre ise sütunun index'idir(4); 

10


Bir sütundaki tum elemanlara ulaşmak

In [0]:
print(myNewArray[:,3]) #tek boyutlu bir dizi döner. ilk parametredeki : => tamamı demektir.

[4 9]


Bir satırdaki elemanlardan belirli sütundaki elemanları yazdırmak

In [0]:
print(myNewArray[1,0:3]) # ilk parametre satırın index'idir. ikinci parametrede sütunun indexleridir. 1 no'lu index'in, 0. sütunundan (0.sütun dahil) 3.sütununa(3.sütun dahil değil) kadar elemanları yazdıralım.

[6 7 8]


İlk satıra ulaşmak:

In [0]:
myNewArray[0,:]

array([1, 2, 3, 4, 5])

İlk Sütuna ulaşmak

In [0]:
myNewArray[:,0]

array([1, 6])

Son satıra ulaşmak

In [0]:
myNewArray[-1,:] #-1 bizim son index'imizdir.

array([ 6,  7,  8,  9, 10])

Son Sütuna ulaşmak

In [0]:
myNewArray[:,-1]

array([ 5, 10])

2  ya da daha fazla uzunluktaki matrisi tek boyutlu matrise çevirme

In [6]:
myNewArray1 = myNewArray.ravel()
myNewArray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

diziyi yeniden boyutlandırma : 2 x 5 => 5 x 2

In [8]:
myNewArray2=myNewArray.reshape(5,2)
myNewArray2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

reshape fonksiyonu orj. diziyi bozmaz.!

In [9]:
myNewArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Orjinal dizinin de değişmesini istiyorsak **resize** fonksiyonu kullanılır.

In [13]:
myNewArray.resize(5,2)
myNewArray # Dikkat edilirse reshape fonksiyonunda değişmiyordu. Ama resize fonksiyonunu çalıştırdığımızda dizimiz de değişti.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Dizileri birleştirme : 
Diziler iki şekilde birleştirilir.


1.   Vertical (Dikey)
2.   Horizontal (Yatay)



In [16]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print("Array1",array1)
print("Array2",array2)

Array1 [[1 2]
 [3 4]]
Array2 [[5 6]
 [7 8]]


Vertical Birleştirme:

In [23]:
arrayv = np.vstack((array1,array2))
print(arrayv)
print("Matris Boyutu",arrayv.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Matris Boyutu (4, 2)


Horizontal Birleştirme

In [25]:
arrayh = np.hstack((array1,array2))
print(arrayh)
print("Matris Boyutu",arrayh.shape)

[[1 2 5 6]
 [3 4 7 8]]
Matris Boyutu (2, 4)


**Not 1 : **  *Print* yazmadan da değişkeni görebilirsiniz. Genelde *print* kullandım. Print komutuna aşinalık oluşması için genelde kullanmaya çalıştım. Ama *print* komutu kullanmadan da değişkeni görebildiğimizi görmeniz açınızdan bazı yerlerde *print* komutu kullanılmamıştır.

**Not 2 : ** Diziler(Array) konusu ile ilgili en çok kullanılan fonksiyon yer almaktadır. Döküman güncellenmektedir. 