<a href="https://colab.research.google.com/github/selimsurucu/numpy/blob/master/numpyBasicMat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

Diziyi random elemanlarla oluşturma

In [15]:
randomDizi = np.random.random((3,3)) # 0 ile 1 arasında random deger üretir.
print(randomDizi)

[[0.73702496 0.01191754 0.08025605]
 [0.94230462 0.55123978 0.72613965]
 [0.78115571 0.62914104 0.26154172]]


Array'in tüm elemanlarını toplamak

In [16]:
print(randomDizi.sum())

4.720721058220735


Array'de ki sütun sütun toplamak

In [19]:
print(randomDizi.sum(axis=0))

[2.46048529 1.19229835 1.06793742]


Array'i satır satır toplamak

In [20]:
print(randomDizi.sum(axis = 1))

[0.82919854 2.21968405 1.67183847]


Bir Array'de ki max değerine ulaşmak

In [17]:
print(randomDizi.max())

0.9423046229195596


Bir Array'de ki min değerine ulaşmak

In [18]:
print(randomDizi.min())

0.0119175359788114


Dizi Oluşturma (İşlemler için) işlemler yapılacağı için boyutu aynı olmalıdır.

In [3]:
a = np.array([5,6,7,8])
b = np.array([1,2,3,4])
print(a)
print(b)

[5 6 7 8]
[1 2 3 4]


2 diziyi toplama

In [4]:
toplam = a+b
print(toplam)

[ 6  8 10 12]


Toplama işleminin numpy'de fonksiyonlu kullanımı

In [23]:
np.add(a,b)

array([ 6,  8, 10, 12])

2 dizide çıkarma yapma

In [25]:
cikarma = a - b
print(cikarma)

[4 4 4 4]


2 arrayı bölme

In [6]:
bolme = a/ b
print(bolme)

[5.         3.         2.33333333 2.        ]


dizi elemanlarının karesinin alınması

In [8]:
aKare = a**2
bKare = b**2
print(aKare)
print(bKare)

[25 36 49 64]
[ 1  4  9 16]


Üssel ifade almanın(**) ifade yerine numpy'de yer alan fonk 

In [22]:
print(np.square(a))
print(np.square(b))

[25 36 49 64]
[ 1  4  9 16]


Bir dizideki elemanlar üzerinde karşılaştırma

In [9]:
aDurum = a<6
print(aDurum)

[ True False False False]


Eleman elamana çarpım işlemi (a'nin 1 i elemanını B'nin 1. elemanıyla çarpma) (Dikkat : Matris çarpımı değil)

In [10]:
carpma = a*b
print(carpma)

[ 5 12 21 32]


bir Matrisin transformu alma = Transform => 2*3'lük bir matris 3*2 lik bir matris olur.

In [12]:
c = np.array([[2,3,5],[3,5,2]])
print(c)
cT = c.T
print(cT)

[[2 3 5]
 [3 5 2]]
[[2 3]
 [3 5]
 [5 2]]


Matris Çarpımı => matris çarpımı yapabilmek için; 2*3'lük bir matris için 3*2'lik bir matris ile çarpılabilir.

In [13]:
matrisCarpim = c.dot(cT)
print(matrisCarpim)

[[38 31]
 [31 38]]


Bir array'in karekökünü alma 

In [21]:
print(np.sqrt(c))

[[1.41421356 1.73205081 2.23606798]
 [1.73205081 2.23606798 1.41421356]]
