<a href="https://colab.research.google.com/github/selimsurucu/numpy/blob/master/NumpyArrayCon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kütüphanesini import ediyoruz.

In [0]:
import numpy as np

Yeni Liste (List) Tanımlama

In [2]:
myList = [1,2,3,4,5,6]
myList

[1, 2, 3, 4, 5, 6]

Dizi Tanımlama : 

In [3]:
myArray=np.array([5,4,3,2]);
myArray #bir array oluştururken aslında fonksiyona parametre olarak bir liste veriliyor.

array([5, 4, 3, 2])

Yani; 
1 Listeyi 1 array'a dönüştürmek istersek: 

In [4]:
newArray = np.array(myList)
newArray

array([1, 2, 3, 4, 5, 6])

Bir arrayi bir listeye dönüştürme

In [6]:
myList = list(newArray)
print(myList)
print(type(myList))

[1, 2, 3, 4, 5, 6]
<class 'list'>


Uygulamalarımızda / çalışmalarımızda Array ve Listeleri birbiri arasında dönüştürmek gerekebilir.
Array -> List,
List -> Array 
**Not:** Pandas ( Numpy gibi bir kütüphane ) kullanırken Liste ile çalışmak genelde daha kolay olur.


Bir arrayi kopyalamak

In [7]:
newArrayCopy = newArray.copy()
newArrayCopy

array([1, 2, 3, 4, 5, 6])

copy fonksiyonu kullanmadan ; newArrayCopy1 = newArray kullansaydık ne olurdu ? 

In [8]:
newArrayCopy1 = newArray
print(newArrayCopy1)
print(newArray)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Peki yeni oluşturduğumuz dizi olan newArrayCopy1 de ilk elemanı 0 yapalım

In [10]:
newArrayCopy1[0] = 0
print(newArrayCopy1)
print(newArray)

[0 2 3 4 5 6]
[0 2 3 4 5 6]


Ama Sadece newArrayCopy1 arrayinde ilk elemanı değiştirmiştik. Ama newArray'in de ilk elamanı değişmiş oldu. Çünkü newArrayCopy1 = newArray atama işlemi yapıldığında pyhton'da iki değişken için aynı hafıza alanını göstermeye devam etmektedir.
Aslında bir bakıma hafızada tasarruf etmeye çalışıyor diye düşünebiliriz.


Peki Copy Kullandığımızda  ne oluyor ? 

In [12]:
newArrayCopy = newArray.copy()
newArrayCopy[2] = 11
print(newArrayCopy)
print(newArray)

[ 0  2 11  4  5  6]
[0 2 3 4 5 6]


newArray yani orjinal fonksiyonumuz aynı kaldı. Çünkü orjinal alanımız copy diyerek içinde ki verimiz yeni bir hafıza bloguna kopyalanmış ve newArrayCopy fonksiyonumuz da bu yeni, kopyalanmış alanı göstermektedir.


Direkt atamak yerine copy() fonksiyonunu kullanmak ; daha güvenli bir kod yazma şeklidir. Eğer direkt atama yapılırsa istemsizce orjinal datada değişiklik ya da bozulma yapılabilir. Bu genelde istenmeyen bir durumdur. Copy Kullanıyoruz :)